apiVersion: v1
kind: Pod
metadata:
  name: loadgenerator
  labels: 
    app: loadgenerator
    run: loadgenerator-slave-1
spec:
  containers:
    - name: loadgenerator-slave-1
      image: descartesresearch/suanming-loadgenerator:latest
   ports:
     - containerPort: 80
     - containerPort: 24226
