apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-slave-1
  labels: 
    app: loadgenerator
    depl: loadgenerator-slave-1
spec:
  selector:
    app: loadgenerator-inst-1
  template:
    metadata:
      labels:
        app: loadgenerator-inst-1
    spec:
      containers:
        - name: loadgenerator-slave
          image: descartesresearch/suanming-loadgenerator:latest
          ports:
          - containerPort: 80
          - containerPort: 24226
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-slave-1
spec:
  selector:
    depl: loadgenerator-slave-1
  ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 24226
  type: ClusterIP
         
