apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-deployments
rules:
  - apiGroups: ["extensions", "apps", ""]
    resources: ["deployments", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]     
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-ctl
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: manage-deployments
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: experiment-1
spec:
  template:
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: internal-kubectl
        image: descartesresearch/suanming-experiment-controller:latest
        command: ["/controller/experiment1.sh"]
        restartPolicy: Never
  backoffLimit: 2
