apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-route-service
spec:
  selector:
    matchLabels:
      app: ts-route-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-route-service
    spec:
      containers:
      - name: ts-route-service
        image: codewisdom/ts-route-service:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 11178
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 11178
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
