apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teastore-registry
spec:
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-registry
    spec:
      containers:
      - name: teastore-registry
        image: descartesresearch/teastore-registry
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
