apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teastore-auth
spec:
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
      - name: teastore-auth
        image: descartesresearch/teastore-auth
        ports:
        - containerPort: 8080
        env:
        - name: HOST_NAME
          value: "teastore-auth"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
