apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teastore-persistence
spec:
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
      - name: teastore-persistence
        image: descartesresearch/teastore-persistence
        ports:
        - containerPort: 8080
        env:
        - name: HOST_NAME
          value: "teastore-persistence"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: DB_HOST
          value: "teastore-db"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
