# This is a basic workflow to build and push the required Docker images
name: Build and Push Images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
          repository: descartesresearch/suanming-experiment-controller
          file: Dockerfile
          path: .
          tags: latest
  loadgenerator:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
          repository: descartesresearch/suanming-loadgenerator
          file: loadgenerator/Dockerfile
          path: loadgenerator/
          tags: latest
